/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Native_Socket */

#ifndef _Included_Native_Socket
#define _Included_Native_Socket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Native_Socket
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Native_Socket_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Native_Socket
 * Method:    send
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_Native_Socket_send
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     Native_Socket
 * Method:    recv
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_Native_Socket_recv
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     Native_Socket
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Native_Socket_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
